### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by schuberty** [schuberty/bitbybit-dungeon#1]
# Bit by Bit Dungeon
- ### *Italic* means *if enough time* to do it

## General
* [ ] FINISH EVERYTHING NEEDED BEFORE **10/12/2019**
* [x] Bitmap Display functions
* [ ] Back coding
* [ ] Data organization
* [ ] **Documentation**
* [x] *Split code in different .asm files by function*

## Bitmap Display
* [x] Rooms background
* [x] Room generation
* [x] Number of rooms to generate and progress icons
* [x] Adventurer generation function
* [x] Enemy generation function
* [x] *Animations*
* [ ] *Secret rooms*
* [x] *Keyboard MMIO Simulator for player movement (animated)*

## Back coding
* [x] Menu
* [ ] *Saving/loading progress*
* [x] In-game menu
* [x] Enemy generation like "blabla wild appears"

## Data organization
* [x] Enemy's config
* [ ] Enemy's phrases
* [ ] *Enemy's phrases as tip for secret rooms*
* [x] Player config
* [x] Menus

## Documentation
